include: package:lint/analysis_options.yaml

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options

analyzer:
  errors:
    # Remove when old theme is removed
    deprecated_member_use: ignore
    # Remove when old theme is removed
    deprecated_member_use_from_same_package: ignore
  exclude:
    - "**/*.doc_widget.dart"
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**

# You can customize the lint rules set to your own liking. A list of all rules
# can be found at https://dart-lang.github.io/linter/lints/options/options.html
linter:
  rules:
    # Util classes are awesome!
    avoid_classes_with_only_static_members: false

    # Make constructors the first thing in every class
    sort_constructors_first: false

    # Choose wisely, but you don't have to
    prefer_double_quotes: true

