// coverage:ignore-file
import "package:client_app_design_system/client_app_design_system.dart";
import "package:flutter/widgets.dart" show IconData;

/// This class has the line version of the icons
class UniconsLineEnum implements EnumDto<IconData> {
  @override
  IconData parse(String enumType) {
    switch (enumType) {
      case "zero_plus":
        return UniconsLine.zero_plus;
      case "three_plus":
        return UniconsLine.three_plus;
      case "six_plus":
        return UniconsLine.six_plus;
      case "ten_plus":
        return UniconsLine.ten_plus;
      case "twelve_plus":
        return UniconsLine.twelve_plus;
      case "thirteen_plus":
        return UniconsLine.thirteen_plus;
      case "sixteen_plus":
        return UniconsLine.sixteen_plus;
      case "seventeen_plus":
        return UniconsLine.seventeen_plus;
      case "eighteen_plus":
        return UniconsLine.eighteen_plus;
      case "twenty_one_plus":
        return UniconsLine.twenty_one_plus;
      case "five_hundred_px":
        return UniconsLine.five_hundred_px;
      case "abacus":
        return UniconsLine.abacus;
      case "accessible_icon_alt":
        return UniconsLine.accessible_icon_alt;
      case "adjust_alt":
        return UniconsLine.adjust_alt;
      case "adjust_circle":
        return UniconsLine.adjust_circle;
      case "adjust_half":
        return UniconsLine.adjust_half;
      case "adjust":
        return UniconsLine.adjust;
      case "adobe_alt":
        return UniconsLine.adobe_alt;
      case "adobe":
        return UniconsLine.adobe;
      case "airplay":
        return UniconsLine.airplay;
      case "align_alt":
        return UniconsLine.align_alt;
      case "align_center_alt":
        return UniconsLine.align_center_alt;
      case "align_center_h":
        return UniconsLine.align_center_h;
      case "align_center_justify":
        return UniconsLine.align_center_justify;
      case "align_center_v":
        return UniconsLine.align_center_v;
      case "align_center":
        return UniconsLine.align_center;
      case "align_justify":
        return UniconsLine.align_justify;
      case "align_left_justify":
        return UniconsLine.align_left_justify;
      case "align_left":
        return UniconsLine.align_left;
      case "align_letter_right":
        return UniconsLine.align_letter_right;
      case "align_right_justify":
        return UniconsLine.align_right_justify;
      case "align_right":
        return UniconsLine.align_right;
      case "align":
        return UniconsLine.align;
      case "amazon":
        return UniconsLine.amazon;
      case "ambulance":
        return UniconsLine.ambulance;
      case "analysis":
        return UniconsLine.analysis;
      case "analytics":
        return UniconsLine.analytics;
      case "anchor":
        return UniconsLine.anchor;
      case "android_alt":
        return UniconsLine.android_alt;
      case "android_phone_slash":
        return UniconsLine.android_phone_slash;
      case "android":
        return UniconsLine.android;
      case "angle_double_down":
        return UniconsLine.angle_double_down;
      case "angle_double_left":
        return UniconsLine.angle_double_left;
      case "angle_double_right":
        return UniconsLine.angle_double_right;
      case "angle_double_up":
        return UniconsLine.angle_double_up;
      case "angle_down":
        return UniconsLine.angle_down;
      case "angle_left_b":
        return UniconsLine.angle_left_b;
      case "angle_left":
        return UniconsLine.angle_left;
      case "angle_right_b":
        return UniconsLine.angle_right_b;
      case "angle_right":
        return UniconsLine.angle_right;
      case "angle_up":
        return UniconsLine.angle_up;
      case "angry":
        return UniconsLine.angry;
      case "ankh":
        return UniconsLine.ankh;
      case "annoyed_alt":
        return UniconsLine.annoyed_alt;
      case "annoyed":
        return UniconsLine.annoyed;
      case "apple_alt":
        return UniconsLine.apple_alt;
      case "apple":
        return UniconsLine.apple;
      case "apps":
        return UniconsLine.apps;
      case "archive_alt":
        return UniconsLine.archive_alt;
      case "archive":
        return UniconsLine.archive;
      case "archway":
        return UniconsLine.archway;
      case "arrow_break":
        return UniconsLine.arrow_break;
      case "arrow_circle_down":
        return UniconsLine.arrow_circle_down;
      case "arrow_circle_left":
        return UniconsLine.arrow_circle_left;
      case "arrow_circle_right":
        return UniconsLine.arrow_circle_right;
      case "arrow_circle_up":
        return UniconsLine.arrow_circle_up;
      case "arrow_compress_h":
        return UniconsLine.arrow_compress_h;
      case "arrow_down_left":
        return UniconsLine.arrow_down_left;
      case "arrow_down_right":
        return UniconsLine.arrow_down_right;
      case "arrow_down":
        return UniconsLine.arrow_down;
      case "arrow_from_right":
        return UniconsLine.arrow_from_right;
      case "arrow_from_top":
        return UniconsLine.arrow_from_top;
      case "arrow_growth":
        return UniconsLine.arrow_growth;
      case "arrow_left":
        return UniconsLine.arrow_left;
      case "arrow_random":
        return UniconsLine.arrow_random;
      case "arrow_resize_diagonal":
        return UniconsLine.arrow_resize_diagonal;
      case "arrow_right":
        return UniconsLine.arrow_right;
      case "arrow_to_bottom":
        return UniconsLine.arrow_to_bottom;
      case "arrow_to_right":
        return UniconsLine.arrow_to_right;
      case "arrow_up_left":
        return UniconsLine.arrow_up_left;
      case "arrow_up_right":
        return UniconsLine.arrow_up_right;
      case "arrow_up":
        return UniconsLine.arrow_up;
      case "arrow":
        return UniconsLine.arrow;
      case "arrows_h_alt":
        return UniconsLine.arrows_h_alt;
      case "arrows_h":
        return UniconsLine.arrows_h;
      case "arrows_left_down":
        return UniconsLine.arrows_left_down;
      case "arrows_maximize":
        return UniconsLine.arrows_maximize;
      case "arrows_merge":
        return UniconsLine.arrows_merge;
      case "arrows_resize_h":
        return UniconsLine.arrows_resize_h;
      case "arrows_resize_v":
        return UniconsLine.arrows_resize_v;
      case "arrows_resize":
        return UniconsLine.arrows_resize;
      case "arrows_right_down":
        return UniconsLine.arrows_right_down;
      case "arrows_shrink_h":
        return UniconsLine.arrows_shrink_h;
      case "arrows_shrink_v":
        return UniconsLine.arrows_shrink_v;
      case "arrows_up_right":
        return UniconsLine.arrows_up_right;
      case "arrows_v_alt":
        return UniconsLine.arrows_v_alt;
      case "arrows_v":
        return UniconsLine.arrows_v;
      case "assistive_listening_systems":
        return UniconsLine.assistive_listening_systems;
      case "asterisk":
        return UniconsLine.asterisk;
      case "at":
        return UniconsLine.at;
      case "atom":
        return UniconsLine.atom;
      case "auto_flash":
        return UniconsLine.auto_flash;
      case "award_alt":
        return UniconsLine.award_alt;
      case "award":
        return UniconsLine.award;
      case "baby_carriage":
        return UniconsLine.baby_carriage;
      case "backpack":
        return UniconsLine.backpack;
      case "backspace":
        return UniconsLine.backspace;
      case "backward":
        return UniconsLine.backward;
      case "bag_alt":
        return UniconsLine.bag_alt;
      case "bag_slash":
        return UniconsLine.bag_slash;
      case "bag":
        return UniconsLine.bag;
      case "balance_scale":
        return UniconsLine.balance_scale;
      case "ban":
        return UniconsLine.ban;
      case "band_aid":
        return UniconsLine.band_aid;
      case "bars":
        return UniconsLine.bars;
      case "baseball_ball":
        return UniconsLine.baseball_ball;
      case "basketball_hoop":
        return UniconsLine.basketball_hoop;
      case "basketball":
        return UniconsLine.basketball;
      case "bath":
        return UniconsLine.bath;
      case "battery_bolt":
        return UniconsLine.battery_bolt;
      case "battery_empty":
        return UniconsLine.battery_empty;
      case "bed_double":
        return UniconsLine.bed_double;
      case "bed":
        return UniconsLine.bed;
      case "behance_alt":
        return UniconsLine.behance_alt;
      case "behance":
        return UniconsLine.behance;
      case "bell_school":
        return UniconsLine.bell_school;
      case "bell_slash":
        return UniconsLine.bell_slash;
      case "bell":
        return UniconsLine.bell;
      case "bill":
        return UniconsLine.bill;
      case "bing":
        return UniconsLine.bing;
      case "bitcoin_alt":
        return UniconsLine.bitcoin_alt;
      case "bitcoin_circle":
        return UniconsLine.bitcoin_circle;
      case "bitcoin_sign":
        return UniconsLine.bitcoin_sign;
      case "bitcoin":
        return UniconsLine.bitcoin;
      case "black_berry":
        return UniconsLine.black_berry;
      case "blogger_alt":
        return UniconsLine.blogger_alt;
      case "blogger":
        return UniconsLine.blogger;
      case "bluetooth_b":
        return UniconsLine.bluetooth_b;
      case "bold":
        return UniconsLine.bold;
      case "bolt_alt":
        return UniconsLine.bolt_alt;
      case "bolt_slash":
        return UniconsLine.bolt_slash;
      case "bolt":
        return UniconsLine.bolt;
      case "book_alt":
        return UniconsLine.book_alt;
      case "book_medical":
        return UniconsLine.book_medical;
      case "book_open":
        return UniconsLine.book_open;
      case "book_reader":
        return UniconsLine.book_reader;
      case "book":
        return UniconsLine.book;
      case "bookmark_full":
        return UniconsLine.bookmark_full;
      case "bookmark":
        return UniconsLine.bookmark;
      case "books":
        return UniconsLine.books;
      case "boombox":
        return UniconsLine.boombox;
      case "border_alt":
        return UniconsLine.border_alt;
      case "border_bottom":
        return UniconsLine.border_bottom;
      case "border_clear":
        return UniconsLine.border_clear;
      case "border_horizontal":
        return UniconsLine.border_horizontal;
      case "border_inner":
        return UniconsLine.border_inner;
      case "border_left":
        return UniconsLine.border_left;
      case "border_out":
        return UniconsLine.border_out;
      case "border_right":
        return UniconsLine.border_right;
      case "border_top":
        return UniconsLine.border_top;
      case "border_vertical":
        return UniconsLine.border_vertical;
      case "bowling_ball":
        return UniconsLine.bowling_ball;
      case "box":
        return UniconsLine.box;
      case "brackets_curly":
        return UniconsLine.brackets_curly;
      case "brain":
        return UniconsLine.brain;
      case "briefcase_alt":
        return UniconsLine.briefcase_alt;
      case "briefcase":
        return UniconsLine.briefcase;
      case "bright":
        return UniconsLine.bright;
      case "brightness_empty":
        return UniconsLine.brightness_empty;
      case "brightness_half":
        return UniconsLine.brightness_half;
      case "brightness_low":
        return UniconsLine.brightness_low;
      case "brightness_minus":
        return UniconsLine.brightness_minus;
      case "brightness_plus":
        return UniconsLine.brightness_plus;
      case "brightness":
        return UniconsLine.brightness;
      case "bring_bottom":
        return UniconsLine.bring_bottom;
      case "bring_front":
        return UniconsLine.bring_front;
      case "browser":
        return UniconsLine.browser;
      case "brush_alt":
        return UniconsLine.brush_alt;
      case "bug":
        return UniconsLine.bug;
      case "building":
        return UniconsLine.building;
      case "bullseye":
        return UniconsLine.bullseye;
      case "bus_alt":
        return UniconsLine.bus_alt;
      case "bus_school":
        return UniconsLine.bus_school;
      case "bus":
        return UniconsLine.bus;
      case "calculator_alt":
        return UniconsLine.calculator_alt;
      case "calculator":
        return UniconsLine.calculator;
      case "calendar_alt":
        return UniconsLine.calendar_alt;
      case "calendar_slash":
        return UniconsLine.calendar_slash;
      case "calender":
        return UniconsLine.calender;
      case "calling":
        return UniconsLine.calling;
      case "camera_change":
        return UniconsLine.camera_change;
      case "camera_plus":
        return UniconsLine.camera_plus;
      case "camera_slash":
        return UniconsLine.camera_slash;
      case "camera":
        return UniconsLine.camera;
      case "cancel":
        return UniconsLine.cancel;
      case "capsule":
        return UniconsLine.capsule;
      case "capture":
        return UniconsLine.capture;
      case "car_sideview":
        return UniconsLine.car_sideview;
      case "car_slash":
        return UniconsLine.car_slash;
      case "car_wash":
        return UniconsLine.car_wash;
      case "car":
        return UniconsLine.car;
      case "card_atm":
        return UniconsLine.card_atm;
      case "caret_right":
        return UniconsLine.caret_right;
      case "cell":
        return UniconsLine.cell;
      case "celsius":
        return UniconsLine.celsius;
      case "channel_add":
        return UniconsLine.channel_add;
      case "channel":
        return UniconsLine.channel;
      case "chart_bar_alt":
        return UniconsLine.chart_bar_alt;
      case "chart_bar":
        return UniconsLine.chart_bar;
      case "chart_down":
        return UniconsLine.chart_down;
      case "chart_growth_alt":
        return UniconsLine.chart_growth_alt;
      case "chart_growth":
        return UniconsLine.chart_growth;
      case "chart_line":
        return UniconsLine.chart_line;
      case "chart_pie_alt":
        return UniconsLine.chart_pie_alt;
      case "chart_pie":
        return UniconsLine.chart_pie;
      case "chart":
        return UniconsLine.chart;
      case "chat_bubble_user":
        return UniconsLine.chat_bubble_user;
      case "chat_info":
        return UniconsLine.chat_info;
      case "chat":
        return UniconsLine.chat;
      case "check_circle":
        return UniconsLine.check_circle;
      case "check_square":
        return UniconsLine.check_square;
      case "check":
        return UniconsLine.check;
      case "circle_layer":
        return UniconsLine.circle_layer;
      case "circle":
        return UniconsLine.circle;
      case "circuit":
        return UniconsLine.circuit;
      case "clapper_board":
        return UniconsLine.clapper_board;
      case "clinic_medical":
        return UniconsLine.clinic_medical;
      case "clipboard_alt":
        return UniconsLine.clipboard_alt;
      case "clipboard_blank":
        return UniconsLine.clipboard_blank;
      case "clipboard_notes":
        return UniconsLine.clipboard_notes;
      case "clipboard":
        return UniconsLine.clipboard;
      case "clock_eight":
        return UniconsLine.clock_eight;
      case "clock_five":
        return UniconsLine.clock_five;
      case "clock_nine":
        return UniconsLine.clock_nine;
      case "clock_seven":
        return UniconsLine.clock_seven;
      case "clock_ten":
        return UniconsLine.clock_ten;
      case "clock_three":
        return UniconsLine.clock_three;
      case "clock_two":
        return UniconsLine.clock_two;
      case "clock":
        return UniconsLine.clock;
      case "closed_captioning_slash":
        return UniconsLine.closed_captioning_slash;
      case "closed_captioning":
        return UniconsLine.closed_captioning;
      case "cloud_block":
        return UniconsLine.cloud_block;
      case "cloud_bookmark":
        return UniconsLine.cloud_bookmark;
      case "cloud_check":
        return UniconsLine.cloud_check;
      case "cloud_computing":
        return UniconsLine.cloud_computing;
      case "cloud_data_connection":
        return UniconsLine.cloud_data_connection;
      case "cloud_database_tree":
        return UniconsLine.cloud_database_tree;
      case "cloud_download":
        return UniconsLine.cloud_download;
      case "cloud_drizzle":
        return UniconsLine.cloud_drizzle;
      case "cloud_exclamation":
        return UniconsLine.cloud_exclamation;
      case "cloud_hail":
        return UniconsLine.cloud_hail;
      case "cloud_heart":
        return UniconsLine.cloud_heart;
      case "cloud_info":
        return UniconsLine.cloud_info;
      case "cloud_lock":
        return UniconsLine.cloud_lock;
      case "cloud_meatball":
        return UniconsLine.cloud_meatball;
      case "cloud_moon_hail":
        return UniconsLine.cloud_moon_hail;
      case "cloud_moon_meatball":
        return UniconsLine.cloud_moon_meatball;
      case "cloud_moon_rain":
        return UniconsLine.cloud_moon_rain;
      case "cloud_moon_showers":
        return UniconsLine.cloud_moon_showers;
      case "cloud_moon":
        return UniconsLine.cloud_moon;
      case "cloud_question":
        return UniconsLine.cloud_question;
      case "cloud_rain_sun":
        return UniconsLine.cloud_rain_sun;
      case "cloud_rain":
        return UniconsLine.cloud_rain;
      case "cloud_redo":
        return UniconsLine.cloud_redo;
      case "cloud_share":
        return UniconsLine.cloud_share;
      case "cloud_shield":
        return UniconsLine.cloud_shield;
      case "cloud_showers_alt":
        return UniconsLine.cloud_showers_alt;
      case "cloud_showers_heavy":
        return UniconsLine.cloud_showers_heavy;
      case "cloud_showers":
        return UniconsLine.cloud_showers;
      case "cloud_slash":
        return UniconsLine.cloud_slash;
      case "cloud_sun_hail":
        return UniconsLine.cloud_sun_hail;
      case "cloud_sun_meatball":
        return UniconsLine.cloud_sun_meatball;
      case "cloud_sun_rain_alt":
        return UniconsLine.cloud_sun_rain_alt;
      case "cloud_sun_rain":
        return UniconsLine.cloud_sun_rain;
      case "cloud_sun_tear":
        return UniconsLine.cloud_sun_tear;
      case "cloud_sun":
        return UniconsLine.cloud_sun;
      case "cloud_times":
        return UniconsLine.cloud_times;
      case "cloud_unlock":
        return UniconsLine.cloud_unlock;
      case "cloud_upload":
        return UniconsLine.cloud_upload;
      case "cloud_wifi":
        return UniconsLine.cloud_wifi;
      case "cloud_wind":
        return UniconsLine.cloud_wind;
      case "cloud":
        return UniconsLine.cloud;
      case "clouds":
        return UniconsLine.clouds;
      case "club":
        return UniconsLine.club;
      case "code_branch":
        return UniconsLine.code_branch;
      case "coffee":
        return UniconsLine.coffee;
      case "cog":
        return UniconsLine.cog;
      case "coins":
        return UniconsLine.coins;
      case "columns":
        return UniconsLine.columns;
      case "comment_add":
        return UniconsLine.comment_add;
      case "comment_alt_block":
        return UniconsLine.comment_alt_block;
      case "comment_alt_chart_lines":
        return UniconsLine.comment_alt_chart_lines;
      case "comment_alt_check":
        return UniconsLine.comment_alt_check;
      case "comment_alt_dots":
        return UniconsLine.comment_alt_dots;
      case "comment_alt_download":
        return UniconsLine.comment_alt_download;
      case "comment_alt_edit":
        return UniconsLine.comment_alt_edit;
      case "comment_alt_exclamation":
        return UniconsLine.comment_alt_exclamation;
      case "comment_alt_heart":
        return UniconsLine.comment_alt_heart;
      case "comment_alt_image":
        return UniconsLine.comment_alt_image;
      case "comment_alt_info":
        return UniconsLine.comment_alt_info;
      case "comment_alt_lines":
        return UniconsLine.comment_alt_lines;
      case "comment_alt_lock":
        return UniconsLine.comment_alt_lock;
      case "comment_alt_medical":
        return UniconsLine.comment_alt_medical;
      case "comment_alt_message":
        return UniconsLine.comment_alt_message;
      case "comment_alt_notes":
        return UniconsLine.comment_alt_notes;
      case "comment_alt_plus":
        return UniconsLine.comment_alt_plus;
      case "comment_alt_question":
        return UniconsLine.comment_alt_question;
      case "comment_alt_redo":
        return UniconsLine.comment_alt_redo;
      case "comment_alt_search":
        return UniconsLine.comment_alt_search;
      case "comment_alt_share":
        return UniconsLine.comment_alt_share;
      case "comment_alt_shield":
        return UniconsLine.comment_alt_shield;
      case "comment_alt_slash":
        return UniconsLine.comment_alt_slash;
      case "comment_alt_upload":
        return UniconsLine.comment_alt_upload;
      case "comment_alt_verify":
        return UniconsLine.comment_alt_verify;
      case "comment_alt":
        return UniconsLine.comment_alt;
      case "comment_block":
        return UniconsLine.comment_block;
      case "comment_chart_line":
        return UniconsLine.comment_chart_line;
      case "comment_check":
        return UniconsLine.comment_check;
      case "comment_dots":
        return UniconsLine.comment_dots;
      case "comment_download":
        return UniconsLine.comment_download;
      case "comment_edit":
        return UniconsLine.comment_edit;
      case "comment_exclamation":
        return UniconsLine.comment_exclamation;
      case "comment_heart":
        return UniconsLine.comment_heart;
      case "comment_image":
        return UniconsLine.comment_image;
      case "comment_info_alt":
        return UniconsLine.comment_info_alt;
      case "comment_info":
        return UniconsLine.comment_info;
      case "comment_lines":
        return UniconsLine.comment_lines;
      case "comment_lock":
        return UniconsLine.comment_lock;
      case "comment_medical":
        return UniconsLine.comment_medical;
      case "comment_message":
        return UniconsLine.comment_message;
      case "comment_notes":
        return UniconsLine.comment_notes;
      case "comment_plus":
        return UniconsLine.comment_plus;
      case "comment_question":
        return UniconsLine.comment_question;
      case "comment_redo":
        return UniconsLine.comment_redo;
      case "comment_search":
        return UniconsLine.comment_search;
      case "comment_share":
        return UniconsLine.comment_share;
      case "comment_shield":
        return UniconsLine.comment_shield;
      case "comment_slash":
        return UniconsLine.comment_slash;
      case "comment_upload":
        return UniconsLine.comment_upload;
      case "comment_verify":
        return UniconsLine.comment_verify;
      case "comment":
        return UniconsLine.comment;
      case "comments_alt":
        return UniconsLine.comments_alt;
      case "comments":
        return UniconsLine.comments;
      case "compact_disc":
        return UniconsLine.compact_disc;
      case "comparison":
        return UniconsLine.comparison;
      case "compass":
        return UniconsLine.compass;
      case "compress_alt_left":
        return UniconsLine.compress_alt_left;
      case "compress_alt":
        return UniconsLine.compress_alt;
      case "compress_arrows":
        return UniconsLine.compress_arrows;
      case "compress_lines":
        return UniconsLine.compress_lines;
      case "compress_point":
        return UniconsLine.compress_point;
      case "compress_v":
        return UniconsLine.compress_v;
      case "compress":
        return UniconsLine.compress;
      case "confused":
        return UniconsLine.confused;
      // case "constructor_1":
      //   return UniconsLine.constructor_1;
      case "copy_alt":
        return UniconsLine.copy_alt;
      case "copy_landscape":
        return UniconsLine.copy_landscape;
      case "copy":
        return UniconsLine.copy;
      case "copyright":
        return UniconsLine.copyright;
      case "corner_down_left":
        return UniconsLine.corner_down_left;
      case "corner_down_right_alt":
        return UniconsLine.corner_down_right_alt;
      case "corner_down_right":
        return UniconsLine.corner_down_right;
      case "corner_left_down":
        return UniconsLine.corner_left_down;
      case "corner_right_down":
        return UniconsLine.corner_right_down;
      case "corner_up_left_alt":
        return UniconsLine.corner_up_left_alt;
      case "corner_up_left":
        return UniconsLine.corner_up_left;
      case "corner_up_right_alt":
        return UniconsLine.corner_up_right_alt;
      case "corner_up_right":
        return UniconsLine.corner_up_right;
      case "coronavirus":
        return UniconsLine.coronavirus;
      case "create_dashboard":
        return UniconsLine.create_dashboard;
      case "creative_commons_pd":
        return UniconsLine.creative_commons_pd;
      case "credit_card_search":
        return UniconsLine.credit_card_search;
      case "credit_card":
        return UniconsLine.credit_card;
      case "crockery":
        return UniconsLine.crockery;
      case "crop_alt_rotate_left":
        return UniconsLine.crop_alt_rotate_left;
      case "crop_alt_rotate_right":
        return UniconsLine.crop_alt_rotate_right;
      case "crop_alt":
        return UniconsLine.crop_alt;
      case "crosshair_alt":
        return UniconsLine.crosshair_alt;
      case "crosshair":
        return UniconsLine.crosshair;
      case "crosshairs":
        return UniconsLine.crosshairs;
      case "css3_simple":
        return UniconsLine.css3_simple;
      case "cube":
        return UniconsLine.cube;
      case "dashboard":
        return UniconsLine.dashboard;
      case "data_sharing":
        return UniconsLine.data_sharing;
      case "database_alt":
        return UniconsLine.database_alt;
      case "database":
        return UniconsLine.database;
      case "desert":
        return UniconsLine.desert;
      case "desktop_alt_slash":
        return UniconsLine.desktop_alt_slash;
      case "desktop_alt":
        return UniconsLine.desktop_alt;
      case "desktop_cloud_alt":
        return UniconsLine.desktop_cloud_alt;
      case "desktop_slash":
        return UniconsLine.desktop_slash;
      case "desktop":
        return UniconsLine.desktop;
      case "dialpad_alt":
        return UniconsLine.dialpad_alt;
      case "dialpad":
        return UniconsLine.dialpad;
      case "diamond":
        return UniconsLine.diamond;
      case "diary_alt":
        return UniconsLine.diary_alt;
      case "diary":
        return UniconsLine.diary;
      case "dice_five":
        return UniconsLine.dice_five;
      case "dice_four":
        return UniconsLine.dice_four;
      case "dice_one":
        return UniconsLine.dice_one;
      case "dice_six":
        return UniconsLine.dice_six;
      case "dice_three":
        return UniconsLine.dice_three;
      case "dice_two":
        return UniconsLine.dice_two;
      case "direction":
        return UniconsLine.direction;
      case "directions":
        return UniconsLine.directions;
      case "discord":
        return UniconsLine.discord;
      case "dizzy_meh":
        return UniconsLine.dizzy_meh;
      case "dna":
        return UniconsLine.dna;
      case "docker":
        return UniconsLine.docker;
      case "document_info":
        return UniconsLine.document_info;
      case "document_layout_center":
        return UniconsLine.document_layout_center;
      case "document_layout_left":
        return UniconsLine.document_layout_left;
      case "document_layout_right":
        return UniconsLine.document_layout_right;
      case "dollar_alt":
        return UniconsLine.dollar_alt;
      case "dollar_sign_alt":
        return UniconsLine.dollar_sign_alt;
      case "dollar_sign":
        return UniconsLine.dollar_sign;
      case "download_alt":
        return UniconsLine.download_alt;
      case "draggabledots":
        return UniconsLine.draggabledots;
      case "dribbble":
        return UniconsLine.dribbble;
      case "drill":
        return UniconsLine.drill;
      case "dropbox":
        return UniconsLine.dropbox;
      case "dumbbell":
        return UniconsLine.dumbbell;
      case "ear":
        return UniconsLine.ear;
      case "edit_alt":
        return UniconsLine.edit_alt;
      case "edit":
        return UniconsLine.edit;
      case "elipsis_double_v_alt":
        return UniconsLine.elipsis_double_v_alt;
      case "ellipsis_h":
        return UniconsLine.ellipsis_h;
      case "ellipsis_v":
        return UniconsLine.ellipsis_v;
      case "emoji":
        return UniconsLine.emoji;
      case "english_to_chinese":
        return UniconsLine.english_to_chinese;
      case "enter":
        return UniconsLine.enter;
      case "envelope_add":
        return UniconsLine.envelope_add;
      case "envelope_alt":
        return UniconsLine.envelope_alt;
      case "envelope_block":
        return UniconsLine.envelope_block;
      case "envelope_bookmark":
        return UniconsLine.envelope_bookmark;
      case "envelope_check":
        return UniconsLine.envelope_check;
      case "envelope_download_alt":
        return UniconsLine.envelope_download_alt;
      case "envelope_download":
        return UniconsLine.envelope_download;
      case "envelope_edit":
        return UniconsLine.envelope_edit;
      case "envelope_exclamation":
        return UniconsLine.envelope_exclamation;
      case "envelope_heart":
        return UniconsLine.envelope_heart;
      case "envelope_info":
        return UniconsLine.envelope_info;
      case "envelope_lock":
        return UniconsLine.envelope_lock;
      case "envelope_minus":
        return UniconsLine.envelope_minus;
      case "envelope_open":
        return UniconsLine.envelope_open;
      case "envelope_question":
        return UniconsLine.envelope_question;
      case "envelope_receive":
        return UniconsLine.envelope_receive;
      case "envelope_redo":
        return UniconsLine.envelope_redo;
      case "envelope_search":
        return UniconsLine.envelope_search;
      case "envelope_send":
        return UniconsLine.envelope_send;
      case "envelope_share":
        return UniconsLine.envelope_share;
      case "envelope_shield":
        return UniconsLine.envelope_shield;
      case "envelope_star":
        return UniconsLine.envelope_star;
      case "envelope_times":
        return UniconsLine.envelope_times;
      case "envelope_upload_alt":
        return UniconsLine.envelope_upload_alt;
      case "envelope_upload":
        return UniconsLine.envelope_upload;
      case "envelope":
        return UniconsLine.envelope;
      case "envelopes":
        return UniconsLine.envelopes;
      case "equal_circle":
        return UniconsLine.equal_circle;
      case "estate":
        return UniconsLine.estate;
      case "euro_circle":
        return UniconsLine.euro_circle;
      case "euro":
        return UniconsLine.euro;
      case "exchange_alt":
        return UniconsLine.exchange_alt;
      case "exchange":
        return UniconsLine.exchange;
      case "exclamation_circle":
        return UniconsLine.exclamation_circle;
      case "exclamation_octagon":
        return UniconsLine.exclamation_octagon;
      case "exclamation_triangle":
        return UniconsLine.exclamation_triangle;
      case "exclamation":
        return UniconsLine.exclamation;
      case "exclude":
        return UniconsLine.exclude;
      case "exit":
        return UniconsLine.exit;
      case "expand_alt":
        return UniconsLine.expand_alt;
      case "expand_arrows_alt":
        return UniconsLine.expand_arrows_alt;
      case "expand_arrows":
        return UniconsLine.expand_arrows;
      case "expand_from_corner":
        return UniconsLine.expand_from_corner;
      case "expand_left":
        return UniconsLine.expand_left;
      case "expand_right":
        return UniconsLine.expand_right;
      // case "export_icon":
      //   return UniconsLine.export_icon;
      case "exposure_alt":
        return UniconsLine.exposure_alt;
      case "exposure_increase":
        return UniconsLine.exposure_increase;
      case "external_link_alt":
        return UniconsLine.external_link_alt;
      case "eye_slash":
        return UniconsLine.eye_slash;
      case "eye":
        return UniconsLine.eye;
      case "facebook_f":
        return UniconsLine.facebook_f;
      case "facebook_messenger_alt":
        return UniconsLine.facebook_messenger_alt;
      case "facebook_messenger":
        return UniconsLine.facebook_messenger;
      case "facebook":
        return UniconsLine.facebook;
      case "fahrenheit":
        return UniconsLine.fahrenheit;
      case "fast_mail_alt":
        return UniconsLine.fast_mail_alt;
      case "fast_mail":
        return UniconsLine.fast_mail;
      case "favorite":
        return UniconsLine.favorite;
      case "feedback":
        return UniconsLine.feedback;
      case "fidget_spinner":
        return UniconsLine.fidget_spinner;
      case "file_alt":
        return UniconsLine.file_alt;
      case "file_blank":
        return UniconsLine.file_blank;
      case "file_block_alt":
        return UniconsLine.file_block_alt;
      case "file_bookmark_alt":
        return UniconsLine.file_bookmark_alt;
      case "file_check_alt":
        return UniconsLine.file_check_alt;
      case "file_check":
        return UniconsLine.file_check;
      case "file_contract_dollar":
        return UniconsLine.file_contract_dollar;
      case "file_contract":
        return UniconsLine.file_contract;
      case "file_copy_alt":
        return UniconsLine.file_copy_alt;
      case "file_download_alt":
        return UniconsLine.file_download_alt;
      case "file_download":
        return UniconsLine.file_download;
      case "file_edit_alt":
        return UniconsLine.file_edit_alt;
      case "file_exclamation_alt":
        return UniconsLine.file_exclamation_alt;
      case "file_exclamation":
        return UniconsLine.file_exclamation;
      case "file_export":
        return UniconsLine.file_export;
      case "file_graph":
        return UniconsLine.file_graph;
      case "file_heart":
        return UniconsLine.file_heart;
      case "file_import":
        return UniconsLine.file_import;
      case "file_info_alt":
        return UniconsLine.file_info_alt;
      case "file_landscape_alt":
        return UniconsLine.file_landscape_alt;
      case "file_landscape":
        return UniconsLine.file_landscape;
      case "file_lanscape_slash":
        return UniconsLine.file_lanscape_slash;
      case "file_lock_alt":
        return UniconsLine.file_lock_alt;
      case "file_medical_alt":
        return UniconsLine.file_medical_alt;
      case "file_medical":
        return UniconsLine.file_medical;
      case "file_minus_alt":
        return UniconsLine.file_minus_alt;
      case "file_minus":
        return UniconsLine.file_minus;
      case "file_network":
        return UniconsLine.file_network;
      case "file_plus_alt":
        return UniconsLine.file_plus_alt;
      case "file_plus":
        return UniconsLine.file_plus;
      case "file_question_alt":
        return UniconsLine.file_question_alt;
      case "file_question":
        return UniconsLine.file_question;
      case "file_redo_alt":
        return UniconsLine.file_redo_alt;
      case "file_search_alt":
        return UniconsLine.file_search_alt;
      case "file_share_alt":
        return UniconsLine.file_share_alt;
      case "file_shield_alt":
        return UniconsLine.file_shield_alt;
      case "file_slash":
        return UniconsLine.file_slash;
      case "file_times_alt":
        return UniconsLine.file_times_alt;
      case "file_times":
        return UniconsLine.file_times;
      case "file_upload_alt":
        return UniconsLine.file_upload_alt;
      case "file_upload":
        return UniconsLine.file_upload;
      case "file":
        return UniconsLine.file;
      case "files_landscapes_alt":
        return UniconsLine.files_landscapes_alt;
      case "files_landscapes":
        return UniconsLine.files_landscapes;
      case "film":
        return UniconsLine.film;
      case "filter_slash":
        return UniconsLine.filter_slash;
      case "filter":
        return UniconsLine.filter;
      case "fire":
        return UniconsLine.fire;
      case "flask_potion":
        return UniconsLine.flask_potion;
      case "flask":
        return UniconsLine.flask;
      case "flip_h_alt":
        return UniconsLine.flip_h_alt;
      case "flip_h":
        return UniconsLine.flip_h;
      case "flip_v_alt":
        return UniconsLine.flip_v_alt;
      case "flip_v":
        return UniconsLine.flip_v;
      case "flower":
        return UniconsLine.flower;
      case "focus_add":
        return UniconsLine.focus_add;
      case "focus_target":
        return UniconsLine.focus_target;
      case "focus":
        return UniconsLine.focus;
      case "folder_check":
        return UniconsLine.folder_check;
      case "folder_download":
        return UniconsLine.folder_download;
      case "folder_exclamation":
        return UniconsLine.folder_exclamation;
      case "folder_heart":
        return UniconsLine.folder_heart;
      case "folder_info":
        return UniconsLine.folder_info;
      case "folder_lock":
        return UniconsLine.folder_lock;
      case "folder_medical":
        return UniconsLine.folder_medical;
      case "folder_minus":
        return UniconsLine.folder_minus;
      case "folder_network":
        return UniconsLine.folder_network;
      case "folder_open":
        return UniconsLine.folder_open;
      case "folder_plus":
        return UniconsLine.folder_plus;
      case "folder_question":
        return UniconsLine.folder_question;
      case "folder_slash":
        return UniconsLine.folder_slash;
      case "folder_times":
        return UniconsLine.folder_times;
      case "folder_upload":
        return UniconsLine.folder_upload;
      case "folder":
        return UniconsLine.folder;
      case "font":
        return UniconsLine.font;
      case "football_american":
        return UniconsLine.football_american;
      case "football_ball":
        return UniconsLine.football_ball;
      case "football":
        return UniconsLine.football;
      case "forecastcloud_moon_tear":
        return UniconsLine.forecastcloud_moon_tear;
      case "forwaded_call":
        return UniconsLine.forwaded_call;
      case "forward":
        return UniconsLine.forward;
      case "frown":
        return UniconsLine.frown;
      case "game_structure":
        return UniconsLine.game_structure;
      case "gift":
        return UniconsLine.gift;
      case "github_alt":
        return UniconsLine.github_alt;
      case "github":
        return UniconsLine.github;
      case "gitlab":
        return UniconsLine.gitlab;
      case "glass_martini_alt_slash":
        return UniconsLine.glass_martini_alt_slash;
      case "glass_martini_alt":
        return UniconsLine.glass_martini_alt;
      case "glass_martini":
        return UniconsLine.glass_martini;
      case "glass_tea":
        return UniconsLine.glass_tea;
      case "glass":
        return UniconsLine.glass;
      case "globe":
        return UniconsLine.globe;
      case "gold":
        return UniconsLine.gold;
      case "golf_ball":
        return UniconsLine.golf_ball;
      case "google_drive_alt":
        return UniconsLine.google_drive_alt;
      case "google_drive":
        return UniconsLine.google_drive;
      case "google_hangouts_alt":
        return UniconsLine.google_hangouts_alt;
      case "google_hangouts":
        return UniconsLine.google_hangouts;
      case "google_play":
        return UniconsLine.google_play;
      case "google":
        return UniconsLine.google;
      case "graduation_cap":
        return UniconsLine.graduation_cap;
      case "graph_bar":
        return UniconsLine.graph_bar;
      case "grid":
        return UniconsLine.grid;
      case "grids":
        return UniconsLine.grids;
      case "grin_tongue_wink_alt":
        return UniconsLine.grin_tongue_wink_alt;
      case "grin_tongue_wink":
        return UniconsLine.grin_tongue_wink;
      case "grin":
        return UniconsLine.grin;
      case "grip_horizontal_line":
        return UniconsLine.grip_horizontal_line;
      case "hard_hat":
        return UniconsLine.hard_hat;
      case "hdd":
        return UniconsLine.hdd;
      case "head_side_cough":
        return UniconsLine.head_side_cough;
      case "head_side_mask":
        return UniconsLine.head_side_mask;
      case "head_side":
        return UniconsLine.head_side;
      case "headphone_slash":
        return UniconsLine.headphone_slash;
      case "headphones_alt":
        return UniconsLine.headphones_alt;
      case "headphones":
        return UniconsLine.headphones;
      case "heart_alt":
        return UniconsLine.heart_alt;
      case "heart_break":
        return UniconsLine.heart_break;
      case "heart_medical":
        return UniconsLine.heart_medical;
      case "heart_rate":
        return UniconsLine.heart_rate;
      case "heart_sign":
        return UniconsLine.heart_sign;
      case "heart":
        return UniconsLine.heart;
      case "heartbeat":
        return UniconsLine.heartbeat;
      case "hindi_to_chinese":
        return UniconsLine.hindi_to_chinese;
      case "hipchat":
        return UniconsLine.hipchat;
      case "history_alt":
        return UniconsLine.history_alt;
      case "history":
        return UniconsLine.history;
      case "home_alt":
        return UniconsLine.home_alt;
      case "home":
        return UniconsLine.home;
      case "horizontal_align_center":
        return UniconsLine.horizontal_align_center;
      case "horizontal_align_left":
        return UniconsLine.horizontal_align_left;
      case "horizontal_align_right":
        return UniconsLine.horizontal_align_right;
      case "horizontal_distribution_center":
        return UniconsLine.horizontal_distribution_center;
      case "horizontal_distribution_left":
        return UniconsLine.horizontal_distribution_left;
      case "horizontal_distribution_right":
        return UniconsLine.horizontal_distribution_right;
      case "hospital_square_sign":
        return UniconsLine.hospital_square_sign;
      case "hospital_symbol":
        return UniconsLine.hospital_symbol;
      case "hospital":
        return UniconsLine.hospital;
      case "hourglass":
        return UniconsLine.hourglass;
      case "house_user":
        return UniconsLine.house_user;
      case "html3_alt":
        return UniconsLine.html3_alt;
      case "html3":
        return UniconsLine.html3;
      case "html5_alt":
        return UniconsLine.html5_alt;
      case "html5":
        return UniconsLine.html5;
      case "hunting":
        return UniconsLine.hunting;
      case "icons":
        return UniconsLine.icons;
      case "illustration":
        return UniconsLine.illustration;
      case "image_alt_slash":
        return UniconsLine.image_alt_slash;
      case "image_block":
        return UniconsLine.image_block;
      case "image_broken":
        return UniconsLine.image_broken;
      case "image_check":
        return UniconsLine.image_check;
      case "image_download":
        return UniconsLine.image_download;
      case "image_edit":
        return UniconsLine.image_edit;
      case "image_lock":
        return UniconsLine.image_lock;
      case "image_minus":
        return UniconsLine.image_minus;
      case "image_plus":
        return UniconsLine.image_plus;
      case "image_question":
        return UniconsLine.image_question;
      case "image_redo":
        return UniconsLine.image_redo;
      case "image_resize_landscape":
        return UniconsLine.image_resize_landscape;
      case "image_resize_square":
        return UniconsLine.image_resize_square;
      case "image_search":
        return UniconsLine.image_search;
      case "image_share":
        return UniconsLine.image_share;
      case "image_shield":
        return UniconsLine.image_shield;
      case "image_slash":
        return UniconsLine.image_slash;
      case "image_times":
        return UniconsLine.image_times;
      case "image_upload":
        return UniconsLine.image_upload;
      case "image_v":
        return UniconsLine.image_v;
      case "image":
        return UniconsLine.image;
      case "images":
        return UniconsLine.images;
      // case "import_icon":
      //   return UniconsLine.import_icon;
      case "inbox":
        return UniconsLine.inbox;
      case "incoming_call":
        return UniconsLine.incoming_call;
      case "info_circle":
        return UniconsLine.info_circle;
      case "info":
        return UniconsLine.info;
      case "instagram_alt":
        return UniconsLine.instagram_alt;
      case "instagram":
        return UniconsLine.instagram;
      case "intercom_alt":
        return UniconsLine.intercom_alt;
      case "intercom":
        return UniconsLine.intercom;
      case "invoice":
        return UniconsLine.invoice;
      case "italic":
        return UniconsLine.italic;
      case "jackhammer":
        return UniconsLine.jackhammer;
      case "java_script":
        return UniconsLine.java_script;
      case "kayak":
        return UniconsLine.kayak;
      case "key_skeleton_alt":
        return UniconsLine.key_skeleton_alt;
      case "key_skeleton":
        return UniconsLine.key_skeleton;
      case "keyboard_alt":
        return UniconsLine.keyboard_alt;
      case "keyboard_hide":
        return UniconsLine.keyboard_hide;
      case "keyboard_show":
        return UniconsLine.keyboard_show;
      case "keyboard":
        return UniconsLine.keyboard;
      case "keyhole_circle":
        return UniconsLine.keyhole_circle;
      case "keyhole_square_full":
        return UniconsLine.keyhole_square_full;
      case "keyhole_square":
        return UniconsLine.keyhole_square;
      case "kid":
        return UniconsLine.kid;
      case "label_alt":
        return UniconsLine.label_alt;
      case "label":
        return UniconsLine.label;
      case "lamp":
        return UniconsLine.lamp;
      case "language":
        return UniconsLine.language;
      case "laptop_cloud":
        return UniconsLine.laptop_cloud;
      case "laptop_connection":
        return UniconsLine.laptop_connection;
      case "laptop":
        return UniconsLine.laptop;
      case "laughing":
        return UniconsLine.laughing;
      case "layer_group_slash":
        return UniconsLine.layer_group_slash;
      case "layer_group":
        return UniconsLine.layer_group;
      case "layers_alt":
        return UniconsLine.layers_alt;
      case "layers_slash":
        return UniconsLine.layers_slash;
      case "layers":
        return UniconsLine.layers;
      case "left_arrow_from_left":
        return UniconsLine.left_arrow_from_left;
      case "left_arrow_to_left":
        return UniconsLine.left_arrow_to_left;
      case "left_indent_alt":
        return UniconsLine.left_indent_alt;
      case "left_indent":
        return UniconsLine.left_indent;
      case "left_to_right_text_direction":
        return UniconsLine.left_to_right_text_direction;
      case "letter_chinese_a":
        return UniconsLine.letter_chinese_a;
      case "letter_english_a":
        return UniconsLine.letter_english_a;
      case "letter_hindi_a":
        return UniconsLine.letter_hindi_a;
      case "letter_japanese_a":
        return UniconsLine.letter_japanese_a;
      case "life_ring":
        return UniconsLine.life_ring;
      case "lightbulb_alt":
        return UniconsLine.lightbulb_alt;
      case "lightbulb":
        return UniconsLine.lightbulb;
      case "line_alt":
        return UniconsLine.line_alt;
      case "line_spacing":
        return UniconsLine.line_spacing;
      case "line":
        return UniconsLine.line;
      case "link_add":
        return UniconsLine.link_add;
      case "link_alt":
        return UniconsLine.link_alt;
      case "link_broken":
        return UniconsLine.link_broken;
      case "link_h":
        return UniconsLine.link_h;
      case "link":
        return UniconsLine.link;
      case "linkedin_alt":
        return UniconsLine.linkedin_alt;
      case "linkedin":
        return UniconsLine.linkedin;
      case "linux":
        return UniconsLine.linux;
      case "lira_sign":
        return UniconsLine.lira_sign;
      case "list_ol_alt":
        return UniconsLine.list_ol_alt;
      case "list_ol":
        return UniconsLine.list_ol;
      case "list_ui_alt":
        return UniconsLine.list_ui_alt;
      case "list_ul":
        return UniconsLine.list_ul;
      case "location_arrow_alt":
        return UniconsLine.location_arrow_alt;
      case "location_arrow":
        return UniconsLine.location_arrow;
      case "location_pin_alt":
        return UniconsLine.location_pin_alt;
      case "location_point":
        return UniconsLine.location_point;
      case "lock_access":
        return UniconsLine.lock_access;
      case "lock_alt":
        return UniconsLine.lock_alt;
      case "lock_open_alt":
        return UniconsLine.lock_open_alt;
      case "lock_slash":
        return UniconsLine.lock_slash;
      case "lock":
        return UniconsLine.lock;
      case "lottiefiles_alt":
        return UniconsLine.lottiefiles_alt;
      case "lottiefiles":
        return UniconsLine.lottiefiles;
      case "luggage_cart":
        return UniconsLine.luggage_cart;
      case "mailbox_alt":
        return UniconsLine.mailbox_alt;
      case "mailbox":
        return UniconsLine.mailbox;
      case "map_marker_alt":
        return UniconsLine.map_marker_alt;
      case "map_marker_edit":
        return UniconsLine.map_marker_edit;
      case "map_marker_info":
        return UniconsLine.map_marker_info;
      case "map_marker_minus":
        return UniconsLine.map_marker_minus;
      case "map_marker_plus":
        return UniconsLine.map_marker_plus;
      case "map_marker_question":
        return UniconsLine.map_marker_question;
      case "map_marker_shield":
        return UniconsLine.map_marker_shield;
      case "map_marker_slash":
        return UniconsLine.map_marker_slash;
      case "map_marker":
        return UniconsLine.map_marker;
      case "map_pin_alt":
        return UniconsLine.map_pin_alt;
      case "map_pin":
        return UniconsLine.map_pin;
      case "map":
        return UniconsLine.map;
      case "mars":
        return UniconsLine.mars;
      case "master_card":
        return UniconsLine.master_card;
      case "maximize_left":
        return UniconsLine.maximize_left;
      case "medal":
        return UniconsLine.medal;
      case "medical_drip":
        return UniconsLine.medical_drip;
      case "medical_square_full":
        return UniconsLine.medical_square_full;
      case "medical_square":
        return UniconsLine.medical_square;
      case "medium_m":
        return UniconsLine.medium_m;
      case "medkit":
        return UniconsLine.medkit;
      case "meeting_board":
        return UniconsLine.meeting_board;
      case "megaphone":
        return UniconsLine.megaphone;
      case "meh_alt":
        return UniconsLine.meh_alt;
      case "meh_closed_eye":
        return UniconsLine.meh_closed_eye;
      case "meh":
        return UniconsLine.meh;
      case "message":
        return UniconsLine.message;
      case "metro":
        return UniconsLine.metro;
      case "microphone_slash":
        return UniconsLine.microphone_slash;
      case "microphone":
        return UniconsLine.microphone;
      case "microscope":
        return UniconsLine.microscope;
      case "microsoft":
        return UniconsLine.microsoft;
      case "minus_circle":
        return UniconsLine.minus_circle;
      case "minus_path":
        return UniconsLine.minus_path;
      case "minus_square_full":
        return UniconsLine.minus_square_full;
      case "minus_square":
        return UniconsLine.minus_square;
      case "minus":
        return UniconsLine.minus;
      case "missed_call":
        return UniconsLine.missed_call;
      case "mobile_android_alt":
        return UniconsLine.mobile_android_alt;
      case "mobile_android":
        return UniconsLine.mobile_android;
      case "mobile_vibrate":
        return UniconsLine.mobile_vibrate;
      case "modem":
        return UniconsLine.modem;
      case "money_bill_slash":
        return UniconsLine.money_bill_slash;
      case "money_bill_stack":
        return UniconsLine.money_bill_stack;
      case "money_bill":
        return UniconsLine.money_bill;
      case "money_insert":
        return UniconsLine.money_insert;
      case "money_stack":
        return UniconsLine.money_stack;
      case "money_withdraw":
        return UniconsLine.money_withdraw;
      case "money_withdrawal":
        return UniconsLine.money_withdrawal;
      case "moneybag_alt":
        return UniconsLine.moneybag_alt;
      case "moneybag":
        return UniconsLine.moneybag;
      case "monitor_heart_rate":
        return UniconsLine.monitor_heart_rate;
      case "monitor":
        return UniconsLine.monitor;
      case "moon_eclipse":
        return UniconsLine.moon_eclipse;
      case "moon":
        return UniconsLine.moon;
      case "moonset":
        return UniconsLine.moonset;
      case "mountains_sun":
        return UniconsLine.mountains_sun;
      case "mountains":
        return UniconsLine.mountains;
      case "mouse_alt_2":
        return UniconsLine.mouse_alt_2;
      case "mouse_alt":
        return UniconsLine.mouse_alt;
      case "mouse":
        return UniconsLine.mouse;
      case "multiply":
        return UniconsLine.multiply;
      case "music_note":
        return UniconsLine.music_note;
      case "music_tune_slash":
        return UniconsLine.music_tune_slash;
      case "music":
        return UniconsLine.music;
      case "n_a":
        return UniconsLine.n_a;
      case "navigator":
        return UniconsLine.navigator;
      case "nerd":
        return UniconsLine.nerd;
      case "newspaper":
        return UniconsLine.newspaper;
      case "ninja":
        return UniconsLine.ninja;
      case "no_entry":
        return UniconsLine.no_entry;
      case "notebooks":
        return UniconsLine.notebooks;
      case "notes":
        return UniconsLine.notes;
      case "object_group":
        return UniconsLine.object_group;
      case "object_ungroup":
        return UniconsLine.object_ungroup;
      case "octagon":
        return UniconsLine.octagon;
      case "okta":
        return UniconsLine.okta;
      case "opera_alt":
        return UniconsLine.opera_alt;
      case "opera":
        return UniconsLine.opera;
      case "outgoing_call":
        return UniconsLine.outgoing_call;
      case "package":
        return UniconsLine.package;
      case "padlock":
        return UniconsLine.padlock;
      case "pagelines":
        return UniconsLine.pagelines;
      case "pagerduty":
        return UniconsLine.pagerduty;
      case "paint_tool":
        return UniconsLine.paint_tool;
      case "palette":
        return UniconsLine.palette;
      case "panel_add":
        return UniconsLine.panel_add;
      case "panorama_h_alt":
        return UniconsLine.panorama_h_alt;
      case "panorama_h":
        return UniconsLine.panorama_h;
      case "panorama_v":
        return UniconsLine.panorama_v;
      case "paperclip":
        return UniconsLine.paperclip;
      case "paragraph":
        return UniconsLine.paragraph;
      case "parcel":
        return UniconsLine.parcel;
      case "parking_circle":
        return UniconsLine.parking_circle;
      case "parking_square":
        return UniconsLine.parking_square;
      case "pathfinder_unite":
        return UniconsLine.pathfinder_unite;
      case "pathfinder":
        return UniconsLine.pathfinder;
      case "pause_circle":
        return UniconsLine.pause_circle;
      case "pause":
        return UniconsLine.pause;
      case "paypal":
        return UniconsLine.paypal;
      case "pen":
        return UniconsLine.pen;
      case "pentagon":
        return UniconsLine.pentagon;
      case "percentage":
        return UniconsLine.percentage;
      case "phone_alt":
        return UniconsLine.phone_alt;
      case "phone_pause":
        return UniconsLine.phone_pause;
      case "phone_slash":
        return UniconsLine.phone_slash;
      case "phone_times":
        return UniconsLine.phone_times;
      case "phone_volume":
        return UniconsLine.phone_volume;
      case "phone":
        return UniconsLine.phone;
      case "picture":
        return UniconsLine.picture;
      case "pizza_slice":
        return UniconsLine.pizza_slice;
      case "plane_arrival":
        return UniconsLine.plane_arrival;
      case "plane_departure":
        return UniconsLine.plane_departure;
      case "plane_fly":
        return UniconsLine.plane_fly;
      case "plane":
        return UniconsLine.plane;
      case "play_circle":
        return UniconsLine.play_circle;
      case "play":
        return UniconsLine.play;
      case "plug":
        return UniconsLine.plug;
      case "plus_circle":
        return UniconsLine.plus_circle;
      case "plus_square":
        return UniconsLine.plus_square;
      case "plus":
        return UniconsLine.plus;
      case "podium":
        return UniconsLine.podium;
      case "polygon":
        return UniconsLine.polygon;
      case "post_stamp":
        return UniconsLine.post_stamp;
      case "postcard":
        return UniconsLine.postcard;
      case "pound_circle":
        return UniconsLine.pound_circle;
      case "pound":
        return UniconsLine.pound;
      case "power":
        return UniconsLine.power;
      case "prescription_bottle":
        return UniconsLine.prescription_bottle;
      case "presentation_check":
        return UniconsLine.presentation_check;
      case "presentation_edit":
        return UniconsLine.presentation_edit;
      case "presentation_line":
        return UniconsLine.presentation_line;
      case "presentation_lines_alt":
        return UniconsLine.presentation_lines_alt;
      case "presentation_minus":
        return UniconsLine.presentation_minus;
      case "presentation_play":
        return UniconsLine.presentation_play;
      case "presentation_plus":
        return UniconsLine.presentation_plus;
      case "presentation_times":
        return UniconsLine.presentation_times;
      case "presentation":
        return UniconsLine.presentation;
      case "previous":
        return UniconsLine.previous;
      case "pricetag_alt":
        return UniconsLine.pricetag_alt;
      case "print_slash":
        return UniconsLine.print_slash;
      case "print":
        return UniconsLine.print;
      case "process":
        return UniconsLine.process;
      case "processor":
        return UniconsLine.processor;
      case "programming_language":
        return UniconsLine.programming_language;
      case "pump":
        return UniconsLine.pump;
      case "puzzle_piece":
        return UniconsLine.puzzle_piece;
      case "qrcode_scan":
        return UniconsLine.qrcode_scan;
      case "question_circle":
        return UniconsLine.question_circle;
      case "question":
        return UniconsLine.question;
      case "rainbow":
        return UniconsLine.rainbow;
      case "raindrops_alt":
        return UniconsLine.raindrops_alt;
      case "raindrops":
        return UniconsLine.raindrops;
      case "react":
        return UniconsLine.react;
      case "receipt_alt":
        return UniconsLine.receipt_alt;
      case "receipt":
        return UniconsLine.receipt;
      case "record_audio":
        return UniconsLine.record_audio;
      case "reddit_alien_alt":
        return UniconsLine.reddit_alien_alt;
      case "redo":
        return UniconsLine.redo;
      case "refresh":
        return UniconsLine.refresh;
      case "registered":
        return UniconsLine.registered;
      case "repeat":
        return UniconsLine.repeat;
      case "restaurant":
        return UniconsLine.restaurant;
      case "right_indent_alt":
        return UniconsLine.right_indent_alt;
      case "right_to_left_text_direction":
        return UniconsLine.right_to_left_text_direction;
      case "robot":
        return UniconsLine.robot;
      case "rocket":
        return UniconsLine.rocket;
      case "rope_way":
        return UniconsLine.rope_way;
      case "rotate_360":
        return UniconsLine.rotate_360;
      case "rss_alt":
        return UniconsLine.rss_alt;
      case "rss_interface":
        return UniconsLine.rss_interface;
      case "rss":
        return UniconsLine.rss;
      case "ruler_combined":
        return UniconsLine.ruler_combined;
      case "ruler":
        return UniconsLine.ruler;
      case "rupee_sign":
        return UniconsLine.rupee_sign;
      case "sad_cry":
        return UniconsLine.sad_cry;
      case "sad_crying":
        return UniconsLine.sad_crying;
      case "sad_dizzy":
        return UniconsLine.sad_dizzy;
      case "sad_squint":
        return UniconsLine.sad_squint;
      case "sad":
        return UniconsLine.sad;
      case "sanitizer_alt":
        return UniconsLine.sanitizer_alt;
      case "sanitizer":
        return UniconsLine.sanitizer;
      case "save":
        return UniconsLine.save;
      case "scaling_left":
        return UniconsLine.scaling_left;
      case "scaling_right":
        return UniconsLine.scaling_right;
      case "scenery":
        return UniconsLine.scenery;
      case "schedule":
        return UniconsLine.schedule;
      case "screw":
        return UniconsLine.screw;
      case "scroll_h":
        return UniconsLine.scroll_h;
      case "scroll":
        return UniconsLine.scroll;
      case "search_alt":
        return UniconsLine.search_alt;
      case "search_minus":
        return UniconsLine.search_minus;
      case "search_plus":
        return UniconsLine.search_plus;
      case "search":
        return UniconsLine.search;
      case "selfie":
        return UniconsLine.selfie;
      case "server_alt":
        return UniconsLine.server_alt;
      case "server_connection":
        return UniconsLine.server_connection;
      case "server_network_alt":
        return UniconsLine.server_network_alt;
      case "server_network":
        return UniconsLine.server_network;
      case "server":
        return UniconsLine.server;
      case "servers":
        return UniconsLine.servers;
      case "servicemark":
        return UniconsLine.servicemark;
      case "setting":
        return UniconsLine.setting;
      case "share_alt":
        return UniconsLine.share_alt;
      case "share":
        return UniconsLine.share;
      case "shield_check":
        return UniconsLine.shield_check;
      case "shield_exclamation":
        return UniconsLine.shield_exclamation;
      case "shield_plus":
        return UniconsLine.shield_plus;
      case "shield_question":
        return UniconsLine.shield_question;
      case "shield_slash":
        return UniconsLine.shield_slash;
      case "shield":
        return UniconsLine.shield;
      case "ship":
        return UniconsLine.ship;
      case "shop":
        return UniconsLine.shop;
      case "shopping_bag":
        return UniconsLine.shopping_bag;
      case "shopping_basket":
        return UniconsLine.shopping_basket;
      case "shopping_cart_alt":
        return UniconsLine.shopping_cart_alt;
      case "shopping_cart":
        return UniconsLine.shopping_cart;
      case "shovel":
        return UniconsLine.shovel;
      case "shrink":
        return UniconsLine.shrink;
      case "shuffle":
        return UniconsLine.shuffle;
      case "shutter_alt":
        return UniconsLine.shutter_alt;
      case "shutter":
        return UniconsLine.shutter;
      case "sick":
        return UniconsLine.sick;
      case "sigma":
        return UniconsLine.sigma;
      case "sign_alt":
        return UniconsLine.sign_alt;
      case "sign_in_alt":
        return UniconsLine.sign_in_alt;
      case "sign_left":
        return UniconsLine.sign_left;
      case "sign_out_alt":
        return UniconsLine.sign_out_alt;
      case "sign_right":
        return UniconsLine.sign_right;
      case "signal_alt_3":
        return UniconsLine.signal_alt_3;
      case "signal_alt":
        return UniconsLine.signal_alt;
      case "signal":
        return UniconsLine.signal;
      case "signin":
        return UniconsLine.signin;
      case "signout":
        return UniconsLine.signout;
      case "silence":
        return UniconsLine.silence;
      case "silent_squint":
        return UniconsLine.silent_squint;
      case "sim_card":
        return UniconsLine.sim_card;
      case "sitemap":
        return UniconsLine.sitemap;
      case "skip_forward_alt":
        return UniconsLine.skip_forward_alt;
      case "skip_forward_circle":
        return UniconsLine.skip_forward_circle;
      case "skip_forward":
        return UniconsLine.skip_forward;
      case "skype_alt":
        return UniconsLine.skype_alt;
      case "skype":
        return UniconsLine.skype;
      case "slack_alt":
        return UniconsLine.slack_alt;
      case "slack":
        return UniconsLine.slack;
      case "slider_h_range":
        return UniconsLine.slider_h_range;
      case "slider_h":
        return UniconsLine.slider_h;
      case "sliders_v_alt":
        return UniconsLine.sliders_v_alt;
      case "sliders_v":
        return UniconsLine.sliders_v;
      case "smile_beam":
        return UniconsLine.smile_beam;
      case "smile_dizzy":
        return UniconsLine.smile_dizzy;
      case "smile_squint_wink_alt":
        return UniconsLine.smile_squint_wink_alt;
      case "smile_squint_wink":
        return UniconsLine.smile_squint_wink;
      case "smile_wink_alt":
        return UniconsLine.smile_wink_alt;
      case "smile_wink":
        return UniconsLine.smile_wink;
      case "smile":
        return UniconsLine.smile;
      case "snapchat_alt":
        return UniconsLine.snapchat_alt;
      case "snapchat_ghost":
        return UniconsLine.snapchat_ghost;
      case "snapchat_square":
        return UniconsLine.snapchat_square;
      case "snow_flake":
        return UniconsLine.snow_flake;
      case "snowflake_alt":
        return UniconsLine.snowflake_alt;
      case "snowflake":
        return UniconsLine.snowflake;
      case "social_distancing":
        return UniconsLine.social_distancing;
      case "sort_amount_down":
        return UniconsLine.sort_amount_down;
      case "sort_amount_up":
        return UniconsLine.sort_amount_up;
      case "sort":
        return UniconsLine.sort;
      case "sorting":
        return UniconsLine.sorting;
      case "space_key":
        return UniconsLine.space_key;
      case "spade":
        return UniconsLine.spade;
      case "sperms":
        return UniconsLine.sperms;
      case "spin":
        return UniconsLine.spin;
      case "spinner_alt":
        return UniconsLine.spinner_alt;
      case "spinner":
        return UniconsLine.spinner;
      case "square_full":
        return UniconsLine.square_full;
      case "square_shape":
        return UniconsLine.square_shape;
      case "square":
        return UniconsLine.square;
      case "squint":
        return UniconsLine.squint;
      case "star_half_alt":
        return UniconsLine.star_half_alt;
      case "star":
        return UniconsLine.star;
      case "step_backward_alt":
        return UniconsLine.step_backward_alt;
      case "step_backward_circle":
        return UniconsLine.step_backward_circle;
      case "step_backward":
        return UniconsLine.step_backward;
      case "step_forward":
        return UniconsLine.step_forward;
      case "stethoscope_alt":
        return UniconsLine.stethoscope_alt;
      case "stethoscope":
        return UniconsLine.stethoscope;
      case "stop_circle":
        return UniconsLine.stop_circle;
      case "stopwatch_slash":
        return UniconsLine.stopwatch_slash;
      case "stopwatch":
        return UniconsLine.stopwatch;
      case "store_alt":
        return UniconsLine.store_alt;
      case "store_slash":
        return UniconsLine.store_slash;
      case "store":
        return UniconsLine.store;
      case "streering":
        return UniconsLine.streering;
      case "stretcher":
        return UniconsLine.stretcher;
      case "subject":
        return UniconsLine.subject;
      case "subway_alt":
        return UniconsLine.subway_alt;
      case "subway":
        return UniconsLine.subway;
      case "suitcase_alt":
        return UniconsLine.suitcase_alt;
      case "suitcase":
        return UniconsLine.suitcase;
      case "sun":
        return UniconsLine.sun;
      case "sunset":
        return UniconsLine.sunset;
      case "surprise":
        return UniconsLine.surprise;
      case "swatchbook":
        return UniconsLine.swatchbook;
      case "swiggy":
        return UniconsLine.swiggy;
      case "swimmer":
        return UniconsLine.swimmer;
      case "sync_exclamation":
        return UniconsLine.sync_exclamation;
      case "sync_slash":
        return UniconsLine.sync_slash;
      // case "sync_icon":
      //   return UniconsLine.sync_icon;
      case "syringe":
        return UniconsLine.syringe;
      case "table_tennis":
        return UniconsLine.table_tennis;
      case "table":
        return UniconsLine.table;
      case "tablet":
        return UniconsLine.tablet;
      case "tablets":
        return UniconsLine.tablets;
      case "tachometer_fast_alt":
        return UniconsLine.tachometer_fast_alt;
      case "tachometer_fast":
        return UniconsLine.tachometer_fast;
      case "tag_alt":
        return UniconsLine.tag_alt;
      case "tag":
        return UniconsLine.tag;
      case "tape":
        return UniconsLine.tape;
      case "taxi":
        return UniconsLine.taxi;
      case "tear":
        return UniconsLine.tear;
      case "telegram_alt":
        return UniconsLine.telegram_alt;
      case "telegram":
        return UniconsLine.telegram;
      case "telescope":
        return UniconsLine.telescope;
      case "temperature_empty":
        return UniconsLine.temperature_empty;
      case "temperature_half":
        return UniconsLine.temperature_half;
      case "temperature_minus":
        return UniconsLine.temperature_minus;
      case "temperature_plus":
        return UniconsLine.temperature_plus;
      case "temperature_quarter":
        return UniconsLine.temperature_quarter;
      case "temperature_three_quarter":
        return UniconsLine.temperature_three_quarter;
      case "temperature":
        return UniconsLine.temperature;
      case "tennis_ball":
        return UniconsLine.tennis_ball;
      case "text_fields":
        return UniconsLine.text_fields;
      case "text_size":
        return UniconsLine.text_size;
      case "text_strike_through":
        return UniconsLine.text_strike_through;
      case "text":
        return UniconsLine.text;
      case "th_large":
        return UniconsLine.th_large;
      case "th_slash":
        return UniconsLine.th_slash;
      case "th":
        return UniconsLine.th;
      case "thermometer":
        return UniconsLine.thermometer;
      case "thumbs_down":
        return UniconsLine.thumbs_down;
      case "thumbs_up":
        return UniconsLine.thumbs_up;
      case "thunderstorm_moon":
        return UniconsLine.thunderstorm_moon;
      case "thunderstorm_sun":
        return UniconsLine.thunderstorm_sun;
      case "thunderstorm":
        return UniconsLine.thunderstorm;
      case "ticket":
        return UniconsLine.ticket;
      case "times_circle":
        return UniconsLine.times_circle;
      case "times_square":
        return UniconsLine.times_square;
      case "times":
        return UniconsLine.times;
      case "toggle_off":
        return UniconsLine.toggle_off;
      case "toggle_on":
        return UniconsLine.toggle_on;
      case "toilet_paper":
        return UniconsLine.toilet_paper;
      case "top_arrow_from_top":
        return UniconsLine.top_arrow_from_top;
      case "top_arrow_to_top":
        return UniconsLine.top_arrow_to_top;
      case "tornado":
        return UniconsLine.tornado;
      case "trademark_circle":
        return UniconsLine.trademark_circle;
      case "trademark":
        return UniconsLine.trademark;
      case "traffic_barrier":
        return UniconsLine.traffic_barrier;
      case "traffic_light":
        return UniconsLine.traffic_light;
      case "transaction":
        return UniconsLine.transaction;
      case "trash_alt":
        return UniconsLine.trash_alt;
      case "trash":
        return UniconsLine.trash;
      case "trees":
        return UniconsLine.trees;
      case "triangle":
        return UniconsLine.triangle;
      case "trophy":
        return UniconsLine.trophy;
      case "trowel":
        return UniconsLine.trowel;
      case "truck_loading":
        return UniconsLine.truck_loading;
      case "truck":
        return UniconsLine.truck;
      case "tumblr_alt":
        return UniconsLine.tumblr_alt;
      case "tumblr_square":
        return UniconsLine.tumblr_square;
      case "tumblr":
        return UniconsLine.tumblr;
      case "tv_retro_slash":
        return UniconsLine.tv_retro_slash;
      case "tv_retro":
        return UniconsLine.tv_retro;
      case "twitter_alt":
        return UniconsLine.twitter_alt;
      case "twitter":
        return UniconsLine.twitter;
      case "umbrella":
        return UniconsLine.umbrella;
      case "unamused":
        return UniconsLine.unamused;
      case "underline":
        return UniconsLine.underline;
      case "university":
        return UniconsLine.university;
      case "unlock_alt":
        return UniconsLine.unlock_alt;
      case "unlock":
        return UniconsLine.unlock;
      case "upload_alt":
        return UniconsLine.upload_alt;
      case "upload":
        return UniconsLine.upload;
      case "usd_circle":
        return UniconsLine.usd_circle;
      case "usd_square":
        return UniconsLine.usd_square;
      case "user_arrows":
        return UniconsLine.user_arrows;
      case "user_check":
        return UniconsLine.user_check;
      case "user_circle":
        return UniconsLine.user_circle;
      case "user_exclamation":
        return UniconsLine.user_exclamation;
      case "user_location":
        return UniconsLine.user_location;
      case "user_md":
        return UniconsLine.user_md;
      case "user_minus":
        return UniconsLine.user_minus;
      case "user_nurse":
        return UniconsLine.user_nurse;
      case "user_plus":
        return UniconsLine.user_plus;
      case "user_square":
        return UniconsLine.user_square;
      case "user_times":
        return UniconsLine.user_times;
      case "user":
        return UniconsLine.user;
      case "users_alt":
        return UniconsLine.users_alt;
      case "utensils_alt":
        return UniconsLine.utensils_alt;
      case "utensils":
        return UniconsLine.utensils;
      case "vector_square_alt":
        return UniconsLine.vector_square_alt;
      case "vector_square":
        return UniconsLine.vector_square;
      case "venus":
        return UniconsLine.venus;
      case "vertical_align_bottom":
        return UniconsLine.vertical_align_bottom;
      case "vertical_align_center":
        return UniconsLine.vertical_align_center;
      case "vertical_align_top":
        return UniconsLine.vertical_align_top;
      case "vertical_distribute_bottom":
        return UniconsLine.vertical_distribute_bottom;
      case "vertical_distribution_center":
        return UniconsLine.vertical_distribution_center;
      case "vertical_distribution_top":
        return UniconsLine.vertical_distribution_top;
      case "video_question":
        return UniconsLine.video_question;
      case "video_slash":
        return UniconsLine.video_slash;
      case "video":
        return UniconsLine.video;
      case "virus_slash":
        return UniconsLine.virus_slash;
      case "visual_studio":
        return UniconsLine.visual_studio;
      case "vk_alt":
        return UniconsLine.vk_alt;
      case "vk":
        return UniconsLine.vk;
      case "voicemail_rectangle":
        return UniconsLine.voicemail_rectangle;
      case "voicemail":
        return UniconsLine.voicemail;
      case "volleyball":
        return UniconsLine.volleyball;
      case "volume_down":
        return UniconsLine.volume_down;
      case "volume_mute":
        return UniconsLine.volume_mute;
      case "volume_off":
        return UniconsLine.volume_off;
      case "volume_up":
        return UniconsLine.volume_up;
      case "volume":
        return UniconsLine.volume;
      case "vuejs_alt":
        return UniconsLine.vuejs_alt;
      case "vuejs":
        return UniconsLine.vuejs;
      case "wall":
        return UniconsLine.wall;
      case "wallet":
        return UniconsLine.wallet;
      case "watch_alt":
        return UniconsLine.watch_alt;
      case "watch":
        return UniconsLine.watch;
      case "water_drop_slash":
        return UniconsLine.water_drop_slash;
      case "water_glass":
        return UniconsLine.water_glass;
      case "water":
        return UniconsLine.water;
      case "web_grid_alt":
        return UniconsLine.web_grid_alt;
      case "web_grid":
        return UniconsLine.web_grid;
      case "web_section_alt":
        return UniconsLine.web_section_alt;
      case "web_section":
        return UniconsLine.web_section;
      case "webcam":
        return UniconsLine.webcam;
      case "weight":
        return UniconsLine.weight;
      case "whatsapp_alt":
        return UniconsLine.whatsapp_alt;
      // case "whatsapp":
      //   return UniconsLine.whatsapp;
      case "wheel_barrow":
        return UniconsLine.wheel_barrow;
      case "wheelchair_alt":
        return UniconsLine.wheelchair_alt;
      case "wheelchair":
        return UniconsLine.wheelchair;
      case "wifi_router":
        return UniconsLine.wifi_router;
      case "wifi_slash":
        return UniconsLine.wifi_slash;
      case "wifi":
        return UniconsLine.wifi;
      case "wind_moon":
        return UniconsLine.wind_moon;
      case "wind_sun":
        return UniconsLine.wind_sun;
      case "wind":
        return UniconsLine.wind;
      case "window_grid":
        return UniconsLine.window_grid;
      case "window_maximize":
        return UniconsLine.window_maximize;
      case "window_section":
        return UniconsLine.window_section;
      case "window":
        return UniconsLine.window;
      case "windows":
        return UniconsLine.windows;
      case "windsock":
        return UniconsLine.windsock;
      case "windy":
        return UniconsLine.windy;
      case "wordpress_simple":
        return UniconsLine.wordpress_simple;
      case "wordpress":
        return UniconsLine.wordpress;
      case "wrap_text":
        return UniconsLine.wrap_text;
      case "wrench":
        return UniconsLine.wrench;
      case "x_add":
        return UniconsLine.x_add;
      case "x":
        return UniconsLine.x;
      case "yen_circle":
        return UniconsLine.yen_circle;
      case "yen":
        return UniconsLine.yen;
      case "yin_yang":
        return UniconsLine.yin_yang;
      case "youtube":
        return UniconsLine.youtube;
      default:
        return UniconsLine.youtube;
    }
  }

  @override
  String stringfy(IconData enumType) {
    throw UnimplementedError();
  }
}
