name: Build android apk

on:
  push:
    tags:
      - v*

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Java Install Step
      uses: actions/setup-java@v1
      with:
        java-version: '12.x'

    - name: Install flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.3.10'
        channel: 'stable'

    - name: Flutter Package Install
      run: flutter pub get

    - name: Flutter Generate Docs
      run: flutter pub run build_runner build --delete-conflicting-outputs

    - name: Build apk android
      run: cd playground && flutter build apk

    - name: Create a Release APK
      uses: ncipollo/release-action@v1
      with:
        artifacts: "playground/build/app/outputs/flutter-apk/*.apk"
        token: ${{ secrets.TOKEN_ACCESS_DOWNLOAD }}